### ISSUE TITLE
The dialog box does not show - Android

### ISSUE THREAD

**Issue by Fudal** [Gimu/admob_consent#1]
Of course there is an instruction in the library in case: 'Consent form does not show up in Android release builds', but I don't know where to find a file where I can change anything.

**Comment by Gimu** [comment]
I can't reproduce your issue, even on a release build, can you check that Funding Choices has been setup correctly for your specific app? I'd wait a bit if you just created your dialog.

The bottom instructions in the README are actually from the older version that used the now deprecated SDK, and I don't think it applies anymore, will be updating the README.

**Comment by Fudal** [comment]
Where I can check setup Funding Choices?

**Comment by Gimu** [comment]
Signing up is described here: https://support.google.com/fundingchoices/answer/9180084
- In AdMob or Ad Manager, click the Privacy & messaging tab in the left menu.
- Click Go to Funding Choices at the top of the page.
- Follow the prompts to create an account, including accepting Funding Choices terms and conditions.

Your apps should be automatically listed there, you just create/customize the dialogs for each app.

**Comment by Fudal** [comment]
@Gimu Thanks for the advice, I have one more question. Do you think that the window should appear every time you open the application? It shouldn't be just once for each device
