### ISSUE TITLE
Is it possible to reset / show the consent dialog again?

### ISSUE THREAD

**Issue by dartsliebe** [Gimu/admob_consent#2]
Is it possible to reset / show the consent dialog again?

**Comment by Gimu** [comment]
It sounds like a good idea to have an argument like `consent.show(forceShow: true)`. I'll do a commit tonight to add this feature, will update this thread then.

**Comment by dartsliebe** [comment]
Great support! Thank you very much for your quick answer! 
I am waiting for your answer :-) Thx!

**Comment by BanhmiDev** [comment]
It has been added, just uploaded `admob_consent: ^1.1.2` with 20e23bb5e5845168b6a471ce887fb34b73392495.

**Comment by tim-tonic** [comment]
I already tried it. Works perfectly. Big thanks!
